cc_library(
    name = "linear_algebra_inplace",
    srcs = ["linear_algebra_inplace.cc"],
    hdrs = ["linear_algebra_inplace.h"],
    visibility = ["//visibility:public"],
    deps = [
	"//tensorflow/core/kernels:linalg_ops_common",
	"//tensorflow/core:framework",
	"//tensorflow/core:lib",
    ]
)

